platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: demo1Spring

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    ls
    apt-get install maven
    chmod +x demo1Spring/mvnw
    ls
    ./mvnw package
    cp ./target/demo-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
