platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: "latest"

inputs:
- name: demo1Spring

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    ls
    chmod +x demo1Spring/mvnw
    cd demo1Spring
    ls
    ./mvnw package
    cp ./target/demo-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
