platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: SpringBootDemo1

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd SpringBootDemo1
    mvn package
    cp ./target/SpringBootDemo1-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
