resources:
- name: SpringBootDemo1
  type: git
  source:
    uri: https://github.com/coxcs1/demo1Spring
    branch: master
- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: coxcs1@etsu.edu
    password: Dog.Bark1();
    organization: coxcs1-org
    space: development

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: SpringBootDemo1, trigger: true}
  - task: build
    privileged: true
    file: SpringBootDemo1/ci/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: SpringBootDemo1/manifest.yml
      path: built-project/demo.jar

