resources:
- name: hello-world
  type: git
  source:
    uri: https://github.com/brooklyyounce/demo1Spring.git
    branch: master
    
- name: cf-deploy-process
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: younceb@goldmail.etsu.edu
    password: Brookly likes the number 47.
    organization: younceb-org
    space: development

jobs:
- name: job-build-deploy
  serial: true
  plan:
  - {get: hello-world, trigger: true}
  - task: build
    file: hello-world/brookly-ci/build.yml
  - put: cf-deploy-process
    params:
      manifest: hello-world/brookly-ci/manifest.yml
      path: built-project/demo.jar